name: deploy
on: 
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Generate build
        run: npm run build

      - name: Create env file
        run: |
          touch .env
          echo VITE_APP_KAKAO_REST_API_KEY=${{ secrets.VITE_APP_KAKAO_REST_API_KEY }} >> .env
          echo VITE_APP_KAKAO_CLIENT_ID={{ secrets.VITE_APP_KAKAO_CLIENT_ID }} >> .env
          echo VITE_APP_KAKAO_JAVASCRIPT_KEY={{ secrets.VITE_APP_KAKAO_JAVASCRIPT_KEY }} >> .env
          echo VITE_APP_KAKAO_REDIRECT_URI={{ secrets.VITE_APP_KAKAO_REDIRECT_URI }} >> .env
          echo VITE_APP_GOOGLE_CLIENT_ID={{ secrets.VITE_APP_GOOGLE_CLIENT_ID }} >> .env
          echo VITE_APP_GOOGLE_REDIRECT_URI={{ secrets.VITE_APP_GOOGLE_REDIRECT_URI }} >> .env
          echo VITE_APP_NAVER_CLIENT_ID={{ secrets.VITE_APP_NAVER_CLIENT_ID }} >> .env
          echo VITE_APP_NAVER_REDIRECT_URI={{ secrets.VITE_APP_NAVER_REDIRECT_URI }} >> .env
          echo VITE_SERVER_URL={{ secrets.VITE_SERVER_URL }} >> .env
          cat .env

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: dist
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          dist-id: ${{ secrets.AWS_CLOUDFRONT_ID }}
          invalidation: / *
